### ISSUE TITLE
Surfing #2

### ISSUE THREAD

**Issue by MartinWessel96** [ProjectBorealis/PBCharacterMovement#25] opened 2021-05-21 14:34 UTC
Hi Sorry i am new to Unreal,
I am trying to get the Surfing feature to work but i could use a little help.

Here is what i have done: 

#ifndef WIP_SURFING
#define WIP_SURFING 50
#endif

public:

#if WIP_SURFING
	void PreemptCollision(float DeltaTime, float SurfaceFriction);
#endif

**Comment by mastercoms** [comment] 2021-05-22 15:52
This is not a support forum. Please ask for help from our community on our Discord. Duplicate of #23.

**Closed by mastercoms** 2021-05-22 15:52 UTC
